universe = vanilla
executable = exe_avg_m1.sh

arguments = $(Run_number)

output = /u/user/swkim/data_certificate/dual-readout_TB/analysis/avgTimeStructure_log/out/o_$(Run_number).out
error = /u/user/swkim/data_certificate/dual-readout_TB/analysis/avgTimeStructure_log/err/e_$(Run_number).err
log = /u/user/swkim/data_certificate/dual-readout_TB/analysis/avgTimeStructure_log/log/l_$(Run_number).log

request_memory = 5 GB

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /u/user/swkim/data_certificate/dual-readout_TB/analysis/TBavgTimeStructure, /u/user/swkim/data_certificate/dual-readout_TB/install/lib64, /u/user/swkim/data_certificate/dual-readout_TB/exe_avg_m1.sh, /u/user/swkim/data_certificate/dual-readout_TB/dwc/dwc_Run_$(Run_number).root, /u/user/swkim/data_certificate/dual-readout_TB/analysis/mapping_Aug2022TB.root, /u/user/swkim/mean/Run$(Run_number)_pedestalHist_mean.root

JobBatchName = draw_avgTimeStructure_m1
queue Run_number from run_list_m1.txt